#!/bin/bash
set -euxo pipefail
exec > >(tee /var/log/ocp-worker-init.log) 2>&1

echo "=== [$(date)] Starting OCP Worker Node Setup ==="

# --- 1. Switch to iptables-nft so our rules and kube-proxy/Calico use the same backend ---
update-alternatives --set iptables  /usr/sbin/iptables-nft
update-alternatives --set ip6tables /usr/sbin/ip6tables-nft

# --- 1b. Allow intra-cluster traffic (OCI Ubuntu image has a REJECT rule by default) ---
iptables -I INPUT -s 192.168.0.0/16 -j ACCEPT
iptables -I INPUT -s 10.96.0.0/12 -j ACCEPT
iptables -I FORWARD -j ACCEPT

# --- 2. Disable swap (required by kubelet) ---
swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# --- 2. Load required kernel modules ---
cat > /etc/modules-load.d/k8s.conf <<EOF
overlay
br_netfilter
EOF
modprobe overlay
modprobe br_netfilter

# --- 3. Sysctl settings for Kubernetes networking ---
cat > /etc/sysctl.d/k8s.conf <<EOF
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF
sysctl --system

# --- 4. Stop apt background work so it cannot grab locks again ---
systemctl stop apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true
systemctl stop apt-daily.service apt-daily-upgrade.service unattended-upgrades.service 2>/dev/null || true
systemctl mask apt-daily.timer apt-daily-upgrade.timer 2>/dev/null || true

wait_for_apt() {
  local lock
  local lock_files=(
    /var/lib/dpkg/lock-frontend
    /var/lib/dpkg/lock
    /var/lib/apt/lists/lock
  )
  for lock in "$${lock_files[@]}"; do
    echo "[$(date)] Waiting for $${lock}..."
    while fuser "$${lock}" >/dev/null 2>&1; do
      pids="$$(fuser "$${lock}" 2>/dev/null | tr -s ' ' ' ')"
      echo "[$(date)] Held by: $${pids}"
      sleep 2
    done
  done
}
wait_for_apt

echo "[$(date)] Cleaning up dpkg interrupts..."
dpkg --configure -a

# --- 4. Install CRI-O v1.32 container runtime ---
CRIO_VERSION=v1.32
apt-get update -y
apt-get install -y apt-transport-https ca-certificates curl gpg

mkdir -p /etc/apt/keyrings
curl -fsSL "https://pkgs.k8s.io/addons:/cri-o:/stable:/$CRIO_VERSION/deb/Release.key" \
  | gpg --batch --yes --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg

echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/$CRIO_VERSION/deb/ /" \
  > /etc/apt/sources.list.d/cri-o.list

apt-get update -y
apt-get install -y cri-o
systemctl enable --now crio
echo "CRI-O status: $(systemctl is-active crio)"

# --- 5. Install Kubernetes v1.32 (kubelet, kubeadm) ---
KUBERNETES_VERSION=v1.32
curl -fsSL "https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/Release.key" \
  | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/$KUBERNETES_VERSION/deb/ /" \
  > /etc/apt/sources.list.d/kubernetes.list

apt-get update -y
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl
systemctl enable --now kubelet

# --- 6. Wait for master API to become ready ---
# Master IP is injected by Terraform at apply time
MASTER_IP="${master_private_ip}"
echo "=== Waiting for master API at https://$MASTER_IP:6443 ==="

until curl -sk "https://$MASTER_IP:6443/healthz" | grep -q ok; do
  echo "[$(date)] Master API not ready yet, retrying in 15s..."
  sleep 15
done

echo "[$(date)] Master API is ready. Joining the cluster..."

# --- 7. Join the Kubernetes cluster ---
# Token is pre-shared (generated by Terraform, same token used in kubeadm init on master)
kubeadm join "$MASTER_IP:6443" \
  --token "${kubeadm_token}" \
  --discovery-token-unsafe-skip-ca-verification

echo "=== [$(date)] OCP Worker Node Successfully Joined Cluster ==="
